# Generated by Django 4.0.6 on 2022-08-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
