# Generated by Django 4.0.6 on 2022-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_product', models.CharField(max_length=2)),
                ('product', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Start_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=1)),
                ('title_banner', models.CharField(max_length=150)),
                ('sub_tittle_banner', models.CharField(max_length=250)),
                ('text_banner', models.CharField(max_length=500)),
                ('img_banner', models.ImageField(upload_to='banner_img')),
            ],
        ),
    ]
