# Generated by Django 4.0.6 on 2022-08-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='start_banner',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customize_page.banner'),
        ),
    ]
