# Generated by Django 4.0.6 on 2022-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0002_banner_alter_start_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=5),
        ),
    ]
