# Generated by Django 4.0.6 on 2022-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0004_alter_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.IntegerField(),
        ),
    ]
