# Generated by Django 4.0.6 on 2022-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0005_alter_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_banner',
            name='banner',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
