# Generated by Django 4.0.6 on 2022-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0007_banner_alter_start_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_banner',
            name='banner',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
