# Generated by Django 4.0.6 on 2022-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0008_alter_start_banner_banner_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_products',
            name='product',
            field=models.CharField(max_length=40),
        ),
    ]
