# Generated by Django 4.0.6 on 2022-09-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize_page', '0009_alter_featured_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_products',
            name='n_product',
        ),
    ]
