# Generated by Django 4.0.6 on 2022-08-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_order_options_order_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_line',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_line',
            old_name='product_id',
            new_name='product',
        ),
    ]
