# Generated by Django 4.0.6 on 2022-08-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_rename_order_id_order_line_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='order_line',
            options={'ordering': ['id'], 'verbose_name': 'Order_line', 'verbose_name_plural': 'Orders_line'},
        ),
    ]
