# Generated by Django 4.0.6 on 2022-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('coulor', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to='img_Product/')),
            ],
        ),
    ]
