# Generated by Django 4.0.6 on 2022-08-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_category',
            field=models.ImageField(null=True, upload_to='img_Category/'),
        ),
    ]
