# Generated by Django 4.0.6 on 2022-08-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_product_category_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=75),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.sub_category'),
        ),
    ]
