# Generated by Django 4.0.6 on 2022-08-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_remove_category_img_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='img_Product/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='img_sub_category',
            field=models.ImageField(default='default.png', null=True, upload_to='img_sub_Category/'),
        ),
    ]
